NAME        = FORMULAS
ICON        = icon.png
DESCRIPTION = "Formula Sheet"
COMPRESSED  = NO
CFLAGS   = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz
ifndef CEDEV
$(error CEDEV environment variable is not set.)
endif
include $(CEDEV)/meta/makefile.mk
